### ISSUE TITLE
Schema configuration model

### ISSUE THREAD

**Issue by aureliano** [aureliano/db-unit-extractor#2]
YAML format.
```yaml
converters:
  - conv1
  - conv2

tables:
  - table: table name
    filters:
      - name: k1
        value: v1
    columns:
      - c1
      - c2
      - c3
    ignore:
      - c4
      - c5
```

After parsing yaml file, it has to validate that:
 - converter name matches any existing converter
 - table name is a valid name
 - key name is a valid name
 - column name is a valid name
 - ignore column name is a valid name
 - a named column must not be in both: columns nor ignore section
