### ISSUE TITLE
Filter template

### ISSUE THREAD

**Issue by aureliano** [aureliano/db-unit-extractor#3]
Let uses of filter template. A filter template has to match these pattern `/\A${(\w+)\.(\w+)}\z/` or `/\A${(\w+)}\z/`. That will be used to match table and column name in order to replace for future queries on dependent tables and environment variables or maybe command line parameters.

```yaml
converters:
  - conv1
  - conv2

tables:
  - table: table_1
    filters:
      - name: k1
        value: ${ENV_VAR}
    columns:
      - id
      - name
      - genre
  - table: table_2
    filters:
      - name: table1_id
        value: ${table_1.id}
```
