### ISSUE TITLE
Allow multivalued parameter

### ISSUE THREAD

**Issue by aureliano** [aureliano/db-unit-extractor#35]
Add support to multivalued parameter. It's necessary when you have multiple records referenced by other recrods. For example, you may have a department that has some employees and employees that have jobs. In a case where you define a data-set schema targeting a specific employee, you'll have an one to many relation.

```yaml
---
tables:
  - name: employees
    filters:
      - name: employee_id
        value: ${employee_id}
  - name: jobs
    filters:
      - name: job_id
        value: ${employees.job_id}
```
In such case, it will result in a data-set with one employee with at least one job. In the other hand, you may have a data-set which target is a department. In that case, you'll have a many to many relation. And you'll need to pass to jobs all employee ids returned by selecting all employees of a given department.

```yaml
tables:
  - name: departments
    filters:
      - name: department_id
        value: ${department_id}
  - name: employees
    filters:
      - name: department_id
        value: ${departments.id}
  - name: jobs
    filters:
      - name: job_id
        value: ${employees.job_id}
```
In this case, it won't work. Instead of referencing employees.job_id, it is necessary to reference all job_ids. An option would be adding `[@]` to the parameter, just like this: `${employees.job_id[@]}`.
