### ISSUE TITLE
Integration test with multivalued parameter

### ISSUE THREAD

**Issue by aureliano** [aureliano/db-unit-extractor#36]
Criar cenário de teste de integração. departments => jobs by employees ou país => jobs by employees
Write an integration test case where a multivalued record is used. Issue #35 must be implemented first.

A good case would be adding jobs referencing employees in departments-ds-model.yml file. Maybe adding this code snippet.

```yaml
- name: jobs
  filters:
    - name: job_id
      value: ${employees.job_id[@]}
- name: job_history
  filters:
    - name: employee_id
      value: ${employees.employee_id[@]}
```
