### ISSUE TITLE
Schema data-set templating

### ISSUE THREAD

**Issue by aureliano** [aureliano/db-unit-extractor#71]
Enable the use of templates in the data schema file so that you can organize the main file and distribute the schema to different files.

The template must be able to handle parameters, the number being variable. However, the path parameter - path to the template file - must be mandatory.

The path parameter can be absolute or relative. When relative, it must be relative to the schema file path that included it.

Example:

```yaml
---
tables:
  - name: customers
    filters:
      - name: id
        value: ${customer_id}
  - name: address
    filters:
      - name: customer_id
        value: ${customer_id}
  <%= template path = "domain-A-tables.yml" customerId = "${customer_id}" %>
  <%= template path = "/home/user/templates/domain-B-tables.yml" param1 = "123" param2 = "${table.pk}" ... %>
```

domain-A-tables.yml

```yaml
  - name: tableA
    filters:
      - name: col1
        value: ${customerId} # same name as passed in template definition.
```
